# Generated by Django 4.0 on 2021-12-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=255)),
                ('emp_id', models.CharField(max_length=15, unique=True)),
                ('emp_finger_id', models.CharField(max_length=255, unique=True)),
                ('emp_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=255)),
                ('emp_designation', models.CharField(default='Software Engineer', max_length=255)),
                ('emp_dept', models.CharField(default='R&D', max_length=255)),
            ],
        ),
    ]
