# Generated by Django 3.2.11 on 2022-03-12 03:44

from django.db import migrations, models
import employee.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=255)),
                ('emp_contact_number', models.CharField(max_length=255)),
                ('emp_id', models.CharField(max_length=15, unique=True)),
                ('emp_finger_id_1', models.CharField(default=employee.models.generate_unique_fid, max_length=255, unique=True)),
                ('emp_finger_id_2', models.CharField(blank=True, default='', max_length=255)),
                ('emp_finger_id_3', models.CharField(blank=True, default='', max_length=255)),
                ('emp_finger_id_4', models.CharField(blank=True, default='', max_length=255)),
                ('emp_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=255)),
                ('emp_designation', models.CharField(default='', max_length=255)),
                ('emp_dept', models.CharField(default='', max_length=255)),
                ('emp_salary_type', models.CharField(choices=[('M', 'Monthly'), ('H', 'Hourly')], max_length=255)),
                ('emp_salary', models.CharField(default='0', max_length=255)),
                ('emp_overtime_per_hour', models.CharField(default='0', max_length=255)),
            ],
        ),
    ]
