# Generated by Django 4.0 on 2021-12-22 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_finger_id_2',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_finger_id_3',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_finger_id_4',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
