# Generated by Django 4.0 on 2021-12-15 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_overtime_per_hour',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_salary',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_salary_type',
            field=models.CharField(choices=[('M', 'Monthly'), ('H', 'Hourly')], default='Monthly', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_dept',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_designation',
            field=models.CharField(default='', max_length=255),
        ),
    ]
