# Generated by Django 3.2.11 on 2022-06-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='rfid_tag_number',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
