# Generated by Django 3.2.11 on 2022-02-03 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employee_emp_finger_id_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_finger_id_2',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_finger_id_3',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_finger_id_4',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
