# Generated by Django 4.0 on 2021-12-15 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_emp_overtime_per_hour_employee_emp_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_contact_number',
            field=models.CharField(default='0101', max_length=255),
            preserve_default=False,
        ),
    ]
