# Generated by Django 4.0 on 2021-12-15 06:58

from django.db import migrations, models
import employee.models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employee_emp_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_finger_id',
            field=models.CharField(default=employee.models.generate_unique_fid, max_length=255, unique=True),
        ),
    ]
