# Generated by Django 3.2.11 on 2023-01-17 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employee_rfid_tag_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_contact_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_salary_type',
            field=models.CharField(blank=True, choices=[('M', 'Monthly'), ('H', 'Hourly')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='rfid_tag_number',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
