# Generated by Django 3.2.11 on 2023-01-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20230117_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='rfid_tag_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
