# Generated by Django 3.2.11 on 2022-11-15 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='template_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_id', models.IntegerField(blank=True, null=True)),
                ('company_name', models.CharField(blank=True, max_length=20, null=True)),
                ('group_id', models.IntegerField(blank=True, null=True)),
                ('temp', models.CharField(blank=True, max_length=4000, null=True)),
                ('flag', models.BooleanField(default=False)),
            ],
        ),
    ]
