# Generated by Django 3.2.11 on 2023-01-06 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceinfo',
            name='device_deptartment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='deviceinfo',
            name='device_emp_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='deviceinfo',
            name='device_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='deviceinfo',
            name='device_name',
            field=models.CharField(default='EMPTY', max_length=255),
        ),
        migrations.AlterField(
            model_name='deviceinfo',
            name='firmware_version',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='firmware',
            name='url',
            field=models.CharField(default='http://credosense.com/downloads', max_length=255),
        ),
        migrations.AlterField(
            model_name='firmware',
            name='version',
            field=models.CharField(default='0.0.1', max_length=255),
        ),
    ]
