# Generated by Django 4.0 on 2021-12-21 05:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commands',
            name='scan_time',
            field=models.DateTimeField(blank=True, default='2021-12-12 08:09:09'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commands',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 21, 5, 46, 0, 650640, tzinfo=utc)),
        ),
    ]
