# Generated by Django 4.0 on 2021-12-22 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commands',
            name='server_message',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
