# Generated by Django 3.2.11 on 2022-01-21 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_commands_server_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='firmware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='deviceinfo',
            name='firmware_version',
            field=models.CharField(default='1.0', max_length=255),
            preserve_default=False,
        ),
    ]
