# Generated by Django 4.0 on 2021-12-21 05:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_commands_scan_time_commands_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commands',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 21, 5, 51, 1, 112671, tzinfo=utc)),
        ),
    ]
