# Generated by Django 4.0 on 2021-12-21 05:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_alter_commands_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commands',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 21, 11, 53, 42, 977543)),
        ),
    ]
