# Generated by Django 3.2.11 on 2022-01-21 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_auto_20220121_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmware',
            name='changelog',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
