# Generated by Django 4.0 on 2021-12-21 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0005_alter_commands_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commands',
            name='scan_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
