# Generated by Django 4.0 on 2021-12-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='settings_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.TimeField(default='08:00:00')),
                ('endTime', models.TimeField(default='17:00:00')),
                ('delayTime', models.TimeField(default='08:15:59')),
                ('offDay', models.TextField(blank=True)),
                ('workDay', models.TextField(blank=True)),
                ('week_saturday', models.BooleanField(default=False)),
                ('week_sunday', models.BooleanField(default=False)),
                ('week_monday', models.BooleanField(default=False)),
                ('week_tuesday', models.BooleanField(default=False)),
                ('week_wednesday', models.BooleanField(default=False)),
                ('week_thursday', models.BooleanField(default=False)),
                ('week_friday', models.BooleanField(default=False)),
            ],
        ),
    ]
