# Generated by Django 4.0 on 2021-12-14 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings_db',
            name='offDay',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='settings_db',
            name='workDay',
            field=models.TextField(blank=True),
        ),
    ]
