# Generated by Django 3.2.11 on 2022-03-12 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_present', models.BooleanField(default=False)),
                ('date', models.DateField(null=True)),
                ('emp_in_time', models.TimeField(blank=True, null=True)),
                ('emp_out_time', models.TimeField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee', to_field='emp_id')),
                ('finger1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finger_id1', to='employee.employee', to_field='emp_finger_id_1')),
            ],
        ),
    ]
