# Generated by Django 4.0 on 2021-12-14 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancelog',
            name='emp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee', to_field='emp_id'),
        ),
    ]
