# Generated by Django 4.0 on 2021-12-22 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancelog',
            name='finger',
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='finger1',
            field=models.ForeignKey(default='assa', on_delete=django.db.models.deletion.CASCADE, related_name='finger_id1', to='employee.employee', to_field='emp_finger_id_1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='finger2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finger_id2', to='employee.employee', to_field='emp_finger_id_2'),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='finger3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finger_id3', to='employee.employee', to_field='emp_finger_id_3'),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='finger4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finger_id4', to='employee.employee', to_field='emp_finger_id_4'),
        ),
    ]
