# Generated by Django 4.0 on 2021-12-14 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('attendance', '0002_alter_attendancelog_emp'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='finger',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='finger_id', to='employee.employee', to_field='emp_finger_id'),
            preserve_default=False,
        ),
    ]
