# Generated by Django 4.0 on 2021-12-22 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_remove_attendancelog_finger_attendancelog_finger1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancelog',
            name='finger2',
        ),
        migrations.RemoveField(
            model_name='attendancelog',
            name='finger3',
        ),
        migrations.RemoveField(
            model_name='attendancelog',
            name='finger4',
        ),
    ]
