# Generated by Django 3.2.9 on 2021-12-07 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendancelog_emp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendancelog',
            old_name='emp',
            new_name='emp_id',
        ),
    ]
