# Generated by Django 3.2.11 on 2022-02-02 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_remove_attendancelog_finger2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
