# Generated by Django 3.2.9 on 2021-12-07 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_rename_emp_attendancelog_emp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancelog',
            name='emp_out_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
