# Generated by Django 3.2.11 on 2022-02-02 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_attendancelog_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancelog',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
    ]
