# Generated by Django 3.2.9 on 2021-12-07 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_alter_attendancelog_emp_out_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancelog',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
