# Generated by Django 3.2.9 on 2021-12-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_alter_attendancelog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancelog',
            name='emp_in_time',
            field=models.TimeField(null=True),
        ),
    ]
